CREATE DATABASE STUDENT
USE STUDENT

CREATE TABLE COLLEGE(
CLG_ID DECIMAL(12) NOT NULL PRIMARY KEY,
CLG_NAME VARCHAR(25) NOT NULL,
DPT_CODE VARCHAR(25) NOT NULL,
DPT_NAME VARCHAR(25) NOT NULL,
DPT_PHONE VARCHAR(25) NOT NULL,
ADV_BLDG VARCHAR(25) NOT NULL,
)

CREATE TABLE STUDENTID(
ST_ID DECIMAL(12) NOT NULL PRIMARY KEY,
ST_LNAME VARCHAR(25) NOT NULL,
ST_MAJOR VARCHAR(25) NOT NULL,
ST_GPA DECIMAL(12) NOT NULL,
ST_HOURS DECIMAL(12) NOT NULL,
ST_LEVEL VARCHAR(20) NOT NULL)

CREATE TABLE ADVISOR(
ADV_PHONE DECIMAL(12) NOT NULL PRIMARY KEY,
ADV_LNAME VARCHAR(25) NOT NULL,
ADV_OFFICE VARCHAR(25) NOT NULL,
)


CREATE TABLE ADMIN (
AdminID DECIMAL(12) NOT NULL PRIMARY KEY,
LastName VARCHAR(25) NOT NULL,
FirstName VARCHAR(25) NOT NULL,
AManagerID DECIMAL(12) NOT NULL, 
FOREIGN KEY (AManagerID) REFERENCES ARTISTMANAGER);